Improve convenience, add -h for help

diff --git a/SinglePointBatch/create b/SinglePointBatch/create
--- a/SinglePointBatch/create
+++ b/SinglePointBatch/create
@@ -1,28 +1,60 @@
 #!bin/bash
 
-# User input
-src=/home-4/yshen57@jhu.edu/data/yshen/C5H9O/Columbus/src # Columbus input template directory
-NAtoms=15
+# Command line input
+usage="Create single point job directories
+
+$(basename "$0") [-h] [-s n]
+                 InputPath NAtoms GeomPath
+
+positional arguments:
+  InputPath      location of Columbus input template
+  NAtoms         number of atoms in the molecule
+  GeomPath       location of the appended geometry file
+
+optional arguments:
+  -h             show this help message and exit
+  -s             skip first n geometry(ies) (default = 0)"
+
+skip=0
+while getopts ':hs:' option; do
+  case "$option" in
+    h) echo "$usage"
+       exit;;
+    s) skip=$OPTARG;;
+    :) printf "missing argument for -%s\n" "$OPTARG" >&2
+       echo "$usage" >&2
+       exit;;
+   \?) printf "illegal option: -%s\n" "$OPTARG" >&2
+       echo "$usage" >&2
+       exit;;
+  esac
+done
+shift $((OPTIND - 1))
 
 # Do the jub
-i=0
+i=1
 count=1
+skip = $[skip*$2] # Actual number of lines to skip
 while read -r line; do
-    if [ $count == 1 ]; then
-        if [ ! -d $i ]; then
-            mkdir $i
-        fi
-        cd $i
-        cp $src/* .
-        echo "$line" > geom
-        count=$[count+1]
-    elif [ $count == $NAtoms ]; then
-        echo "$line" >> geom
-        cd ..
-        i=$[i+1]
-        count=1
+    if [ $skip > 0 ]; then
+        skip=$[skip-1]
     else
-        echo "$line" >> geom
-        count=$[count+1]
+        if [ $count == 1 ]; then # Start a new geometry
+            if [ ! -d $i ]; then
+                mkdir $i
+            fi
+            cd $i
+            cp $1/* .
+            echo "$line" > geom
+            count=$[count+1]
+        elif [ $count == $2 ]; then # End of current geometry
+            echo "$line" >> geom
+            cd ..
+            i=$[i+1]
+            count=1
+        else # Keep working on current geometry
+            echo "$line" >> geom
+            count=$[count+1]
+        fi
     fi
-done < geom.all
+done < $3
diff --git a/SinglePointBatch/submit b/SinglePointBatch/submit
--- a/SinglePointBatch/submit
+++ b/SinglePointBatch/submit
@@ -1,20 +1,54 @@
 #!bin/bash
 
-# This is to resubmit failed Columbus7 job or submit new job. Take an argument $1 = NDirectory
+# Command line input
+usage="Submit new Columbus7 job or resubmit failed job
 
-for ((i=0; i<$1; i++)); do
-    cd $i
-    if [ -f 'runc.log' ]; then
-        success=`cat runc.log |grep timings`
-        if [ ! -n "$success" ]; then
-            if [ ! -d WORK ]; then
-                echo 'Failed job '$i
+$(basename "$0") [-h] [-s n]
+
+optional arguments:
+  -h             show this help message and exit
+  -s             queuing system (default = slurm)"
+
+queue='slurm'
+while getopts ':hs:' option; do
+  case "$option" in
+    h) echo "$usage"
+       exit;;
+    s) queue=$OPTARG;;
+    :) printf "missing argument for -%s\n" "$OPTARG" >&2
+       echo "$usage" >&2
+       exit;;
+   \?) printf "illegal option: -%s\n" "$OPTARG" >&2
+       echo "$usage" >&2
+       exit;;
+  esac
+done
+shift $((OPTIND - 1))
+
+# Do the job
+for entry in * ; do
+    if [ -d $entry ]; then # This is a directory
+        cd $entry
+        if [ -f 'geom' ]; then # This is a job directory
+            if [ ! -f 'runc.log' ]; then # This is a new job
+                cp ../RunColumbus .
                 sbatch RunColumbus
+            else # This job has started
+                success=`cat runc.log |grep timings`
+                if [ ! -n "$success" ]; then # This job has not yet succeeded
+                    error=`cat runc.log |grep 'Error occured!'`
+                    timeout=`cat ${queue}* |grep TIMEOUT`
+                    if [ -n "${error}${timeout}" ]; then # This job has failed
+                        echo 'Failed job '$entry
+                        if [ -d WORK ]; then # Remove Columbus7 scratch
+                            rm -r WORK
+                        fi
+                        rm ${queue}* # Remove queuing system log
+                        sbatch RunColumbus
+                    fi
+                fi
             fi
         fi
-    else
-        cp ../RunColumbus ./
-        sbatch RunColumbus
+        cd ..
     fi
-    cd ..
 done
